[package]
name = "rustystm32"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.5"
panic-halt = "1.0.0"
cortex-m = "0.7.3"

[default]
chip = "STM32F401RE" # Nombre exacto del microcontrolador

[flashing]
halt_afterwards = false
reset_after_flashing = false
