[package]
name = "rusty-stm32"
version = "0.1.0"
edition = "2021"

[dependencies]
stm32f4xx-hal = { version = "0.22.1", features = ["stm32f401"] }
cortex-m-rt = "0.7.5"
cortex-m = "0.7.3"
panic-halt = "0.2.0"
